front/src/pages/index.tsx
=> fix: added condition in useEffect to prevent duplicated events

front/package.json, front/src/components/RoomsCanvas/RoomsImageStore.ts
=> feat: refresh UI with requestAnimationFrame

apps/frontend/src/components/saveur/RestaurantCardStore.ts, apps/frontend/src/components/saveur/restaurants/RatingComponent.tsx, apps/frontend/src/components/saveur/restaurants/RestaurantCard.tsx
Ajout du système de notation des restaurants
closes #21
=> feat: restaurant ratings

apps/frontend/src/pages/saveur/restaurants/Ratings.tsx
=> fix: ratings display

apps/backend/app/Controllers/Http/AdminController/routes/editUserRights.ts, apps/backend/app/Controllers/Http/RestaurantsController/routes/store.ts, apps/frontend/src/globalStores/EventsStore.ts, apps/frontend/src/globalStores/RestaurantsStore.ts, apps/frontend/src/pages/saveur/restaurants/RestaurantCardStore.ts, apps/frontend/src/pages/saveur/restaurants/RestaurantMarkers.tsx, apps/frontend/src/pages/saveur/restaurants/createEdit/RestaurantStore.ts, apps/frontend/src/reusableComponents/auth/WhoamiStore.ts
=> fix: fixed typos

apps/frontend/src/pages/admin/dashboard/DashboardStore.ts, apps/frontend/src/pages/admin/rights/EditUserRightsStore.ts
=> fix: more typo

apps/frontend/src/pages/admin/rights/EditUserRights.tsx
This PR adds the possibility to give a user `DASHBOARD_ADMIN` rights from the edit user page.
=> feat: added possibility to add dashboard admin in user administration

apps/backend/app/Models/Idea.ts, apps/frontend/src/pages/idea/Idea.tsx, apps/frontend/src/pages/idea/IdeaPage.tsx, apps/frontend/src/pages/idea/IdeasStore.ts, libs/shared/src/idea/idea.ts
=> Add username and creation date of idea on the card

apps/frontend/index.html, apps/frontend/src/pages/idea/IdeaPage.tsx
=> fix: idea page

apps/backend/app/Controllers/Http/statistics/StatisticsController.ts, apps/backend/app/Controllers/Http/statistics/getEventsAmountPerGaladrimeurs.ts, apps/backend/app/Controllers/Http/statistics/getGaladrimeurFavoriteRooms.ts, apps/backend/app/Controllers/Http/statistics/getTimePerGaladrimeurs.ts, apps/frontend/src/pages/statistics/StatisticsPage.tsx, apps/frontend/src/pages/statistics/StatisticsStore.ts
Switch button to choose between stats overall or last 30 days
Routes update to include optional query parameters
closes #61
=> feat: statistics 30 days or all

apps/frontend/src/pages/statistics/StatisticsStore.ts
=> fix: time formatting was module day duration

apps/frontend/src/pages/idea/Idea.tsx, apps/frontend/src/utils/patchNotesInfos.ts
=> added version notes

apps/frontend/src/pages/saveur/restaurants/Ratings.tsx, apps/frontend/src/pages/saveur/restaurants/RestaurantCard.tsx
=> Don't change reaction on restaurant when clicking on bar

apps/frontend/src/pages/saveur/myRestaurantNotes/MyRestaurantNotesPage.tsx, libs/shared/src/saveur/notes.ts
This PR adds real filtering on restaurant notes.
=> feat: myRestaurantNotes filtering

apps/frontend/src/pages/saveur/myRestaurantNotes/MyRestaurantNotesPage.tsx
This PR fixes restaurant notes filtering by dates.
=> fix: restaurantNotes date sorting

.vscode/settings.json, apps/frontend/index.html, apps/frontend/src/pages/HomePage.tsx, apps/frontend/src/pages/idea/CommentIdeaModal.tsx, apps/frontend/src/pages/idea/DisplayIdeas.tsx, apps/frontend/src/pages/idea/Idea.tsx, apps/frontend/src/pages/idea/IdeaPage.tsx, apps/frontend/src/reusableComponents/common/IconLink.tsx, apps/frontend/src/reusableComponents/layouts/MainLayout.tsx, apps/frontend/src/theme/index.ts
This PR adds responsiveness of idea page, as suggested by Jean in one of the ideas.
=> feat: responsiveness of idea page

apps/frontend/src/pages/idea/CommentIdeaModal.tsx, apps/frontend/src/pages/idea/CreateIdeaModal.tsx, apps/frontend/src/pages/idea/Idea.tsx, apps/frontend/src/pages/idea/IdeaPage.tsx, apps/frontend/src/reusableComponents/form/TextInputWithIcon.tsx
=> feat: added possibility to break lines

apps/frontend/src/pages/profile/notifications/NotificationsSettingsPage.tsx
Changement du nom du type de notification par Fanny
=> fix: label notification FANNICHOU

apps/backend/app/Controllers/Http/restaurants/storeRestaurant.ts, apps/backend/app/Controllers/Http/restaurants/updateRestaurant.ts, apps/backend/app/Models/Restaurant.ts, apps/backend/database/migrations/1701111853006_add_website_links.ts, apps/backend/package.json, apps/frontend/package.json, apps/frontend/src/globalStores/RestaurantsStore.ts, apps/frontend/src/pages/saveur/restaurants/RestaurantCard.tsx, apps/frontend/src/pages/saveur/restaurants/UserDailyChoices.tsx, apps/frontend/src/pages/saveur/restaurants/createEdit/EditRestaurant.tsx, apps/frontend/src/pages/saveur/restaurants/createEdit/RestaurantStore.ts, apps/frontend/src/reusableComponents/patchNotes/PatchNotes.tsx, apps/frontend/src/utils/patchNotesInfos.ts, libs/shared/src/saveur/saveurTypes.ts, package.json
In this PR :
- Add possibility to give a link for restaurant
- Add redirection to restaurant card form daily choices
- Add patch contributors
=> feat: added link to restaurant and daily choices redirection

apps/frontend/src/pages/room/RoomCalendar.tsx, apps/frontend/src/pages/room/RoomPage.tsx, apps/frontend/src/reusableComponents/WorkplaceSvg/WorkplaceSvg.tsx, apps/frontend/src/reusableComponents/WorkplaceSvg/WorkplaceWorkersSvg.tsx, apps/frontend/src/reusableComponents/auth/Whoami.tsx, apps/frontend/src/reusableComponents/layouts/MainLayout.tsx, apps/frontend/src/utils/rooms.ts
=> Add new phone box

apps/backend/app/Controllers/Http/events/availableRooms.ts, apps/frontend/src/pages/room/RoomCalendar.tsx, apps/frontend/src/pages/room/RoomPage.tsx, apps/frontend/src/reusableComponents/WorkplaceSvg/WorkplaceSvg.tsx, apps/frontend/src/utils/rooms.ts
Add Nantes room reservations possibilities
=> Add nantes room reservations

.vscode/extensions.json, .vscode/settings.json
=> chore: added VSCode Biome extension recommendation + formatter default settings

apps/frontend/src/routes/MainRouter.tsx
This reverts commit c53157e62356a5af8a0bc6f08041016d44c2f2a3.
=> Revert "feat: add snow"
